# -*- coding: utf-8 -*-
"""CHDModel

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wZZzGn90nIYqgkYeNZVJvcWTSvKbeS5s
"""

# Commented out IPython magic to ensure Python compatibility.
try:
#   %tensorflow_version 2.x
except Exception:
  pass

from __future__ import absolute_import, division, print_function, unicode_literals
import functools

import numpy as np
import tensorflow as tf

from google.colab import files
uploaded = files.upload()

train_file_path = "heart_train.csv"
test_file_path = "heart_test.csv"

# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

!head {train_file_path}

# The only column you need to identify explicitly is the one with the value that the model is intended to predict.
LABEL_COLUMN = 'chd'
LABELS = [0, 1]

# read the CSV data from the file and create two datasets for training and testing

def get_dataset(file, **kwargs):
  dataset = tf.data.experimental.make_csv_dataset(
      file,
      batch_size = 50,
      label_name=LABEL_COLUMN,
      na_value ="?",
      num_epochs=1,
      ignore_errors=True,
      **kwargs)
  return dataset

info = ['sbp','tobacco','ldl','adiposity','famhist', 'typea','obesity','alcohol','age','chd']
raw_train_data = get_dataset(train_file_path, select_columns=info)
raw_test_data = get_dataset(test_file_path, select_columns=info)

def show_batch(dataset):
  for batch, label in dataset.take(1):
    for key, value in batch.items():
      print("{:20s}: {}".format(key,value.numpy()))

show_batch(raw_train_data)

test_batch, labels_batch = next(iter(raw_test_data))
train_batch, labels_batch = next(iter(raw_train_data))

# simple function that packs together all the columns
def pack(features, label):
  return tf.stack(list(features.values()), axis=-1), label

# define a more general preprocessor that selects a list of numeric features and packs them into a single column:
class PackNumericFeatures(object):
  def __init__(self, names):
    self.names = names

  def __call__(self, features, labels):
    numeric_features = [features.pop(name) for name in self.names]
    numeric_features = [tf.cast(feat, tf.float32) for feat in numeric_features]
    numeric_features = tf.stack(numeric_features, axis=-1)
    features['numeric'] = numeric_features

    return features, labels

NUMERIC_FEATURES = ['sbp','tobacco','ldl','adiposity', 'typea','obesity','alcohol','age']

packed_train_data = raw_train_data.map(
    PackNumericFeatures(NUMERIC_FEATURES))

packed_test_data = raw_test_data.map(
    PackNumericFeatures(NUMERIC_FEATURES))

show_batch(packed_train_data)

train_batch, label_batch = next(iter(packed_train_data))
test_batch, label_batch = next(iter(packed_test_data))

# data normalization

import pandas as pd
desc = pd.read_csv(train_file_path)[NUMERIC_FEATURES].describe()
desc

MEAN = np.array(desc.T['mean'])
STD = np.array(desc.T['std'])

def normalize_numeric_data(data, mean, std):
  # Center the data
  return (data-mean)/std

# See what you just created.
normalizer = functools.partial(normalize_numeric_data, mean=MEAN, std=STD)

numeric_column = tf.feature_column.numeric_column('numeric', normalizer_fn=normalizer, shape=[len(NUMERIC_FEATURES)])
numeric_columns = [numeric_column]
numeric_column

train_batch['numeric']

numeric_layer = tf.keras.layers.DenseFeatures(numeric_columns)
numeric_layer(train_batch).numpy()

CATEGORIES = {
    'famhist': ['Absent', 'Present']
}

categorical_columns = []
for feature, vocab in CATEGORIES.items():
  cat_col = tf.feature_column.categorical_column_with_vocabulary_list(
        key=feature, vocabulary_list=vocab)
  categorical_columns.append(tf.feature_column.indicator_column(cat_col))

# See what you just created.
categorical_columns

categorical_layer = tf.keras.layers.DenseFeatures(categorical_columns)
print(categorical_layer(train_batch).numpy()[0])

#Combined preprocessing layer
#Add the two feature column collections and pass them to a tf.keras.layers.DenseFeatures to create an input layer that will extract and preprocess both input types:

preprocessing_layer = tf.keras.layers.DenseFeatures(categorical_columns+numeric_columns)

print(preprocessing_layer(train_batch).numpy()[0])

# build the model

model = tf.keras.Sequential([
  preprocessing_layer,
  tf.keras.layers.Dense(128, kernel_regularizer=tf.keras.regularizers.l2(0.01), activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(128, kernel_regularizer=tf.keras.regularizers.l2(0.01), activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(128, kernel_regularizer=tf.keras.regularizers.l2(0.01), activation='relu'),
  tf.keras.layers.Dropout(0.2),

  tf.keras.layers.Dense(1, activation='sigmoid'),
])

model.compile(
    loss='binary_crossentropy',
    optimizer='adamax',
    metrics=['accuracy'])

train_data = packed_train_data.shuffle(600)
test_data = packed_test_data

model.fit(train_data, epochs=400)

train_loss, train_accuracy = model.evaluate(train_data)

print('\n\nTrain Loss {:.4f}, Train Accuracy {:.2%}'.format(train_loss, train_accuracy))

test_loss, test_accuracy = model.evaluate(test_data)

print('\n\nTest Loss {:.4f}, Test Accuracy {:.2%}'.format(test_loss, test_accuracy))

predictions = model.predict(test_data)

# Show some results
for prediction, CHD in zip(predictions[:10], list(test_data)[0][1][:10]):
  print("Predicted diagnosis certainty: {:.2%}".format(prediction[0]),
        " | Actual outcome: ",
        ("Patient has CHD" if bool(CHD) else "Patient doesn't have CHD"))